services:
  # Node.js service (use with: docker compose up gigarino --build)
  gigarino:
    build:
      context: .
      dockerfile: Dockerfile
    image: gigarino
    container_name: gigarino-container
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped